[package]
name = "picer"
version = "0.1.0"
authors = ["realth000 <a598919335@gmail.com>"]
edition = "2021"

[profile.release]
lto = true

[dependencies]
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gtk = { version = "0.7", package = "gtk4", features = ["v4_8"] }
tracing = "0.1.37"
tracing-subscriber = "0.3"
